//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mukha4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Город.
    /// </summary>
    // *** Start programmer edit section *** (Город CustomAttributes)

    // *** End programmer edit section *** (Город CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГородE", new string[] {
            "Название as \'Название\'",
            "Широта as \'Широта\'",
            "IDИдентификатор as \'I d идентификатор\'",
            "Долгота as \'Долгота\'"})]
    [View("ГородL", new string[] {
            "Название as \'Название\'",
            "Широта as \'Широта\'",
            "IDИдентификатор as \'I d идентификатор\'",
            "Долгота as \'Долгота\'"})]
    public class Город : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private double fШирота;
        
        private int fIDИдентификатор;
        
        private double fДолгота;
        
        // *** Start programmer edit section *** (Город CustomMembers)

        // *** End programmer edit section *** (Город CustomMembers)

        
        /// <summary>
        /// IDИдентификатор.
        /// </summary>
        // *** Start programmer edit section *** (Город.IDИдентификатор CustomAttributes)

        // *** End programmer edit section *** (Город.IDИдентификатор CustomAttributes)
        public virtual int IDИдентификатор
        {
            get
            {
                // *** Start programmer edit section *** (Город.IDИдентификатор Get start)

                // *** End programmer edit section *** (Город.IDИдентификатор Get start)
                int result = this.fIDИдентификатор;
                // *** Start programmer edit section *** (Город.IDИдентификатор Get end)

                // *** End programmer edit section *** (Город.IDИдентификатор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Город.IDИдентификатор Set start)

                // *** End programmer edit section *** (Город.IDИдентификатор Set start)
                this.fIDИдентификатор = value;
                // *** Start programmer edit section *** (Город.IDИдентификатор Set end)

                // *** End programmer edit section *** (Город.IDИдентификатор Set end)
            }
        }
        
        /// <summary>
        /// Долгота.
        /// </summary>
        // *** Start programmer edit section *** (Город.Долгота CustomAttributes)

        // *** End programmer edit section *** (Город.Долгота CustomAttributes)
        public virtual double Долгота
        {
            get
            {
                // *** Start programmer edit section *** (Город.Долгота Get start)

                // *** End programmer edit section *** (Город.Долгота Get start)
                double result = this.fДолгота;
                // *** Start programmer edit section *** (Город.Долгота Get end)

                // *** End programmer edit section *** (Город.Долгота Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Город.Долгота Set start)

                // *** End programmer edit section *** (Город.Долгота Set start)
                this.fДолгота = value;
                // *** Start programmer edit section *** (Город.Долгота Set end)

                // *** End programmer edit section *** (Город.Долгота Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Город.Название CustomAttributes)

        // *** End programmer edit section *** (Город.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Город.Название Get start)

                // *** End programmer edit section *** (Город.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Город.Название Get end)

                // *** End programmer edit section *** (Город.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Город.Название Set start)

                // *** End programmer edit section *** (Город.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Город.Название Set end)

                // *** End programmer edit section *** (Город.Название Set end)
            }
        }
        
        /// <summary>
        /// Широта.
        /// </summary>
        // *** Start programmer edit section *** (Город.Широта CustomAttributes)

        // *** End programmer edit section *** (Город.Широта CustomAttributes)
        public virtual double Широта
        {
            get
            {
                // *** Start programmer edit section *** (Город.Широта Get start)

                // *** End programmer edit section *** (Город.Широта Get start)
                double result = this.fШирота;
                // *** Start programmer edit section *** (Город.Широта Get end)

                // *** End programmer edit section *** (Город.Широта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Город.Широта Set start)

                // *** End programmer edit section *** (Город.Широта Set start)
                this.fШирота = value;
                // *** Start programmer edit section *** (Город.Широта Set end)

                // *** End programmer edit section *** (Город.Широта Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГородE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГородE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГородE", typeof(IIS.Mukha4.Город));
                }
            }
            
            /// <summary>
            /// "ГородL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГородL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГородL", typeof(IIS.Mukha4.Город));
                }
            }
        }
    }
}
