//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mukha4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Здание.
    /// </summary>
    // *** Start programmer edit section *** (Здание CustomAttributes)

    // *** End programmer edit section *** (Здание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗданиеE", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Долгота as \'Долгота\'",
            "Широта as \'Широта\'",
            "ГородID as \'Город ID\'",
            "IDИдентификатор as \'I d идентификатор\'"})]
    [View("ЗданиеL", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'",
            "Долгота as \'Долгота\'",
            "Широта as \'Широта\'",
            "ГородID as \'Город ID\'",
            "IDИдентификатор as \'I d идентификатор\'"})]
    public class Здание : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fАдрес;
        
        private double fДолгота;
        
        private double fШирота;
        
        private int fГородID;
        
        private int fIDИдентификатор;
        
        private IIS.Mukha4.Город fГород;
        
        // *** Start programmer edit section *** (Здание CustomMembers)

        // *** End programmer edit section *** (Здание CustomMembers)

        
        /// <summary>
        /// IDИдентификатор.
        /// </summary>
        // *** Start programmer edit section *** (Здание.IDИдентификатор CustomAttributes)

        // *** End programmer edit section *** (Здание.IDИдентификатор CustomAttributes)
        public virtual int IDИдентификатор
        {
            get
            {
                // *** Start programmer edit section *** (Здание.IDИдентификатор Get start)

                // *** End programmer edit section *** (Здание.IDИдентификатор Get start)
                int result = this.fIDИдентификатор;
                // *** Start programmer edit section *** (Здание.IDИдентификатор Get end)

                // *** End programmer edit section *** (Здание.IDИдентификатор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.IDИдентификатор Set start)

                // *** End programmer edit section *** (Здание.IDИдентификатор Set start)
                this.fIDИдентификатор = value;
                // *** Start programmer edit section *** (Здание.IDИдентификатор Set end)

                // *** End programmer edit section *** (Здание.IDИдентификатор Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Адрес CustomAttributes)

        // *** End programmer edit section *** (Здание.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Адрес Get start)

                // *** End programmer edit section *** (Здание.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Здание.Адрес Get end)

                // *** End programmer edit section *** (Здание.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Адрес Set start)

                // *** End programmer edit section *** (Здание.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Здание.Адрес Set end)

                // *** End programmer edit section *** (Здание.Адрес Set end)
            }
        }
        
        /// <summary>
        /// ГородID.
        /// </summary>
        // *** Start programmer edit section *** (Здание.ГородID CustomAttributes)

        // *** End programmer edit section *** (Здание.ГородID CustomAttributes)
        public virtual int ГородID
        {
            get
            {
                // *** Start programmer edit section *** (Здание.ГородID Get start)

                // *** End programmer edit section *** (Здание.ГородID Get start)
                int result = this.fГородID;
                // *** Start programmer edit section *** (Здание.ГородID Get end)

                // *** End programmer edit section *** (Здание.ГородID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.ГородID Set start)

                // *** End programmer edit section *** (Здание.ГородID Set start)
                this.fГородID = value;
                // *** Start programmer edit section *** (Здание.ГородID Set end)

                // *** End programmer edit section *** (Здание.ГородID Set end)
            }
        }
        
        /// <summary>
        /// Долгота.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Долгота CustomAttributes)

        // *** End programmer edit section *** (Здание.Долгота CustomAttributes)
        public virtual double Долгота
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Долгота Get start)

                // *** End programmer edit section *** (Здание.Долгота Get start)
                double result = this.fДолгота;
                // *** Start programmer edit section *** (Здание.Долгота Get end)

                // *** End programmer edit section *** (Здание.Долгота Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Долгота Set start)

                // *** End programmer edit section *** (Здание.Долгота Set start)
                this.fДолгота = value;
                // *** Start programmer edit section *** (Здание.Долгота Set end)

                // *** End programmer edit section *** (Здание.Долгота Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Название CustomAttributes)

        // *** End programmer edit section *** (Здание.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Название Get start)

                // *** End programmer edit section *** (Здание.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Здание.Название Get end)

                // *** End programmer edit section *** (Здание.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Название Set start)

                // *** End programmer edit section *** (Здание.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Здание.Название Set end)

                // *** End programmer edit section *** (Здание.Название Set end)
            }
        }
        
        /// <summary>
        /// Широта.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Широта CustomAttributes)

        // *** End programmer edit section *** (Здание.Широта CustomAttributes)
        public virtual double Широта
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Широта Get start)

                // *** End programmer edit section *** (Здание.Широта Get start)
                double result = this.fШирота;
                // *** Start programmer edit section *** (Здание.Широта Get end)

                // *** End programmer edit section *** (Здание.Широта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Широта Set start)

                // *** End programmer edit section *** (Здание.Широта Set start)
                this.fШирота = value;
                // *** Start programmer edit section *** (Здание.Широта Set end)

                // *** End programmer edit section *** (Здание.Широта Set end)
            }
        }
        
        /// <summary>
        /// Здание.
        /// </summary>
        // *** Start programmer edit section *** (Здание.Город CustomAttributes)

        // *** End programmer edit section *** (Здание.Город CustomAttributes)
        [PropertyStorage(new string[] {
                "Город"})]
        [NotNull()]
        public virtual IIS.Mukha4.Город Город
        {
            get
            {
                // *** Start programmer edit section *** (Здание.Город Get start)

                // *** End programmer edit section *** (Здание.Город Get start)
                IIS.Mukha4.Город result = this.fГород;
                // *** Start programmer edit section *** (Здание.Город Get end)

                // *** End programmer edit section *** (Здание.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Здание.Город Set start)

                // *** End programmer edit section *** (Здание.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (Здание.Город Set end)

                // *** End programmer edit section *** (Здание.Город Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗданиеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеE", typeof(IIS.Mukha4.Здание));
                }
            }
            
            /// <summary>
            /// "ЗданиеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗданиеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗданиеL", typeof(IIS.Mukha4.Здание));
                }
            }
        }
    }
}
