//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Mukha4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Метеостанция.
    /// </summary>
    // *** Start programmer edit section *** (Метеостанция CustomAttributes)

    // *** End programmer edit section *** (Метеостанция CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МетеостанцияE", new string[] {
            "Название as \'Название\'",
            "IDИдентификатор as \'I d идентификатор\'",
            "Местоположение as \'Местоположение\'",
            "Широта as \'Широта\'",
            "Долгота as \'Долгота\'",
            "ГородID as \'Город ID\'",
            "Влажность as \'Влажность\'"})]
    [View("МетеостанцияL", new string[] {
            "Название as \'Название\'",
            "IDИдентификатор as \'I d идентификатор\'",
            "Местоположение as \'Местоположение\'",
            "Широта as \'Широта\'",
            "Долгота as \'Долгота\'",
            "ГородID as \'Город ID\'",
            "Влажность as \'Влажность\'"})]
    public class Метеостанция : ICSSoft.STORMNET.DataObject
    {
        
        private double fТекущаяТемп;
        
        private string fНазвание;
        
        private int fIDИдентификатор;
        
        private string fМестоположение;
        
        private double fШирота;
        
        private double fДолгота;
        
        private int fГородID;
        
        private double fВлажность;
        
        private IIS.Mukha4.Город fГород;
        
        // *** Start programmer edit section *** (Метеостанция CustomMembers)

        // *** End programmer edit section *** (Метеостанция CustomMembers)

        
        /// <summary>
        /// IDИдентификатор.
        /// </summary>
        // *** Start programmer edit section *** (Метеостанция.IDИдентификатор CustomAttributes)

        // *** End programmer edit section *** (Метеостанция.IDИдентификатор CustomAttributes)
        public virtual int IDИдентификатор
        {
            get
            {
                // *** Start programmer edit section *** (Метеостанция.IDИдентификатор Get start)

                // *** End programmer edit section *** (Метеостанция.IDИдентификатор Get start)
                int result = this.fIDИдентификатор;
                // *** Start programmer edit section *** (Метеостанция.IDИдентификатор Get end)

                // *** End programmer edit section *** (Метеостанция.IDИдентификатор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Метеостанция.IDИдентификатор Set start)

                // *** End programmer edit section *** (Метеостанция.IDИдентификатор Set start)
                this.fIDИдентификатор = value;
                // *** Start programmer edit section *** (Метеостанция.IDИдентификатор Set end)

                // *** End programmer edit section *** (Метеостанция.IDИдентификатор Set end)
            }
        }
        
        /// <summary>
        /// Влажность.
        /// </summary>
        // *** Start programmer edit section *** (Метеостанция.Влажность CustomAttributes)

        // *** End programmer edit section *** (Метеостанция.Влажность CustomAttributes)
        public virtual double Влажность
        {
            get
            {
                // *** Start programmer edit section *** (Метеостанция.Влажность Get start)

                // *** End programmer edit section *** (Метеостанция.Влажность Get start)
                double result = this.fВлажность;
                // *** Start programmer edit section *** (Метеостанция.Влажность Get end)

                // *** End programmer edit section *** (Метеостанция.Влажность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Метеостанция.Влажность Set start)

                // *** End programmer edit section *** (Метеостанция.Влажность Set start)
                this.fВлажность = value;
                // *** Start programmer edit section *** (Метеостанция.Влажность Set end)

                // *** End programmer edit section *** (Метеостанция.Влажность Set end)
            }
        }
        
        /// <summary>
        /// ГородID.
        /// </summary>
        // *** Start programmer edit section *** (Метеостанция.ГородID CustomAttributes)

        // *** End programmer edit section *** (Метеостанция.ГородID CustomAttributes)
        public virtual int ГородID
        {
            get
            {
                // *** Start programmer edit section *** (Метеостанция.ГородID Get start)

                // *** End programmer edit section *** (Метеостанция.ГородID Get start)
                int result = this.fГородID;
                // *** Start programmer edit section *** (Метеостанция.ГородID Get end)

                // *** End programmer edit section *** (Метеостанция.ГородID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Метеостанция.ГородID Set start)

                // *** End programmer edit section *** (Метеостанция.ГородID Set start)
                this.fГородID = value;
                // *** Start programmer edit section *** (Метеостанция.ГородID Set end)

                // *** End programmer edit section *** (Метеостанция.ГородID Set end)
            }
        }
        
        /// <summary>
        /// Долгота.
        /// </summary>
        // *** Start programmer edit section *** (Метеостанция.Долгота CustomAttributes)

        // *** End programmer edit section *** (Метеостанция.Долгота CustomAttributes)
        public virtual double Долгота
        {
            get
            {
                // *** Start programmer edit section *** (Метеостанция.Долгота Get start)

                // *** End programmer edit section *** (Метеостанция.Долгота Get start)
                double result = this.fДолгота;
                // *** Start programmer edit section *** (Метеостанция.Долгота Get end)

                // *** End programmer edit section *** (Метеостанция.Долгота Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Метеостанция.Долгота Set start)

                // *** End programmer edit section *** (Метеостанция.Долгота Set start)
                this.fДолгота = value;
                // *** Start programmer edit section *** (Метеостанция.Долгота Set end)

                // *** End programmer edit section *** (Метеостанция.Долгота Set end)
            }
        }
        
        /// <summary>
        /// Местоположение.
        /// </summary>
        // *** Start programmer edit section *** (Метеостанция.Местоположение CustomAttributes)

        // *** End programmer edit section *** (Метеостанция.Местоположение CustomAttributes)
        [StrLen(255)]
        public virtual string Местоположение
        {
            get
            {
                // *** Start programmer edit section *** (Метеостанция.Местоположение Get start)

                // *** End programmer edit section *** (Метеостанция.Местоположение Get start)
                string result = this.fМестоположение;
                // *** Start programmer edit section *** (Метеостанция.Местоположение Get end)

                // *** End programmer edit section *** (Метеостанция.Местоположение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Метеостанция.Местоположение Set start)

                // *** End programmer edit section *** (Метеостанция.Местоположение Set start)
                this.fМестоположение = value;
                // *** Start programmer edit section *** (Метеостанция.Местоположение Set end)

                // *** End programmer edit section *** (Метеостанция.Местоположение Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Метеостанция.Название CustomAttributes)

        // *** End programmer edit section *** (Метеостанция.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Метеостанция.Название Get start)

                // *** End programmer edit section *** (Метеостанция.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Метеостанция.Название Get end)

                // *** End programmer edit section *** (Метеостанция.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Метеостанция.Название Set start)

                // *** End programmer edit section *** (Метеостанция.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Метеостанция.Название Set end)

                // *** End programmer edit section *** (Метеостанция.Название Set end)
            }
        }
        
        /// <summary>
        /// ТекущаяТемп.
        /// </summary>
        // *** Start programmer edit section *** (Метеостанция.ТекущаяТемп CustomAttributes)

        // *** End programmer edit section *** (Метеостанция.ТекущаяТемп CustomAttributes)
        public virtual double ТекущаяТемп
        {
            get
            {
                // *** Start programmer edit section *** (Метеостанция.ТекущаяТемп Get start)

                // *** End programmer edit section *** (Метеостанция.ТекущаяТемп Get start)
                double result = this.fТекущаяТемп;
                // *** Start programmer edit section *** (Метеостанция.ТекущаяТемп Get end)

                // *** End programmer edit section *** (Метеостанция.ТекущаяТемп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Метеостанция.ТекущаяТемп Set start)

                // *** End programmer edit section *** (Метеостанция.ТекущаяТемп Set start)
                this.fТекущаяТемп = value;
                // *** Start programmer edit section *** (Метеостанция.ТекущаяТемп Set end)

                // *** End programmer edit section *** (Метеостанция.ТекущаяТемп Set end)
            }
        }
        
        /// <summary>
        /// Широта.
        /// </summary>
        // *** Start programmer edit section *** (Метеостанция.Широта CustomAttributes)

        // *** End programmer edit section *** (Метеостанция.Широта CustomAttributes)
        public virtual double Широта
        {
            get
            {
                // *** Start programmer edit section *** (Метеостанция.Широта Get start)

                // *** End programmer edit section *** (Метеостанция.Широта Get start)
                double result = this.fШирота;
                // *** Start programmer edit section *** (Метеостанция.Широта Get end)

                // *** End programmer edit section *** (Метеостанция.Широта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Метеостанция.Широта Set start)

                // *** End programmer edit section *** (Метеостанция.Широта Set start)
                this.fШирота = value;
                // *** Start programmer edit section *** (Метеостанция.Широта Set end)

                // *** End programmer edit section *** (Метеостанция.Широта Set end)
            }
        }
        
        /// <summary>
        /// Метеостанция.
        /// </summary>
        // *** Start programmer edit section *** (Метеостанция.Город CustomAttributes)

        // *** End programmer edit section *** (Метеостанция.Город CustomAttributes)
        [PropertyStorage(new string[] {
                "Город"})]
        [NotNull()]
        public virtual IIS.Mukha4.Город Город
        {
            get
            {
                // *** Start programmer edit section *** (Метеостанция.Город Get start)

                // *** End programmer edit section *** (Метеостанция.Город Get start)
                IIS.Mukha4.Город result = this.fГород;
                // *** Start programmer edit section *** (Метеостанция.Город Get end)

                // *** End programmer edit section *** (Метеостанция.Город Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Метеостанция.Город Set start)

                // *** End programmer edit section *** (Метеостанция.Город Set start)
                this.fГород = value;
                // *** Start programmer edit section *** (Метеостанция.Город Set end)

                // *** End programmer edit section *** (Метеостанция.Город Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МетеостанцияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МетеостанцияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МетеостанцияE", typeof(IIS.Mukha4.Метеостанция));
                }
            }
            
            /// <summary>
            /// "МетеостанцияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МетеостанцияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МетеостанцияL", typeof(IIS.Mukha4.Метеостанция));
                }
            }
        }
    }
}
